spring.application.name=demo

# Configuración de la conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase?options=-c%20timezone=UTC
spring.datasource.hikari.data-source-properties.options=-c timezone=UTC
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
# 'update' actualiza el esquema automáticamente (útil en desarrollo)
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en la consola
spring.jpa.show-sql=true

# Formatea el SQL para que sea legible
spring.jpa.properties.hibernate.format_sql=true

# Dialecto específico para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Exponer todos los endpoints de Actuator por la Web (HTTP)
management.endpoints.web.exposure.include=*
